// These styles apply to every route in the application



import Header from '@/components/Header'
import './globals.css'
import Footer from '@/components/Footer'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header /> {/* If this is fixed/absolute, it might overlap content */}
        <main className=""> {/* Add top padding */}
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
